### ISSUE TITLE
Explicitly refer to powershell.exe

### ISSUE THREAD

**Issue by Sleavely** [Sleavely/win-screenoff#1]
Running `npx win-screenoff` in a WSL environment results in an error because the shorthand `powershell` doesn't exist in PATH. It can probably be solved by explicitly appending `.exe` to the command:

```
👉 npx win-screenoff
npx: installed 6 in 5.839s
Something went horribly wrong. Do you have Powershell installed? Error: spawn powershell ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn powershell',
  path: 'powershell',
  spawnargs: [
    '-NoProfile',
    '-Command',
    '& {\n' +
      "    Add-Type -TypeDefinition '\n" +
      '    using System;\n' +
      '    using System.Runtime.InteropServices;\n' +
      '\n' +
      '    namespace Utilities {\n' +
      '      public static class Display\n' +
      '      {\n' +
      '          [DllImport("user32.dll", CharSet = CharSet.Auto)]\n' +
      '          private static extern IntPtr SendMessage(\n' +
      '            IntPtr hWnd,\n' +
      '            UInt32 Msg,\n' +
      '            IntPtr wParam,\n' +
      '            IntPtr lParam\n' +
      '          );\n' +
      '\n' +
      '          public static void PowerOff ()\n' +
      '          {\n' +
      '            SendMessage(\n' +
      '                (IntPtr)0xffff, // HWND_BROADCAST\n' +
      '                0x0112,         // WM_SYSCOMMAND\n' +
      '                (IntPtr)0xf170, // SC_MONITORPOWER\n' +
      '                (IntPtr)0x0002  // POWER_OFF\n' +
      '            );\n' +
      '          }\n' +
      '      }\n' +
      '    }\n' +
      "    '\n" +
      '    [Utilities.Display]::PowerOff()\n' +
      '    }'
  ]
}
```

**Comment by Sleavely** [comment]
Related reading for detecting which environment we're in:

https://github.com/IonicaBizau/powershell/blob/master/lib/index.js

https://github.com/IonicaBizau/is-win/blob/master/lib/index.js

https://github.com/ericcornelissen/shescape/blob/main/src/win.js
